import {
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage2,
  chromecast,
  disc02,
  discord,
  discordBlack,
  facebook,
  figma,
  file02,
  hacker,
  shell,
  git,
  bug,
  memory,
  linux,
  network,
  framer,
  homeSmile,
  instagram,
  notification2,
  notification3,
  notification4,
  notion,
  photoshop,
  plusSquare,
  protopie,
  raindrop,
  recording01,
  recording03,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  searchMd,
  slack,
  sliders04,
  telegram,
  twitter,
  yourlogo,
} from "../assets";

const timelineElements = [
  {
    id: 1,
    title: "Flowcharts & Algorithms",
    location: "Bu-Ali Sina University",
    description:
      "Learn how to design flowcharts and understand fundamental algorithms for problem solving.",
    buttonText: "View Notes",
    date: "Week 1 - 2",
    iconSrc: file02,
    icon: "work",
  },
  {
    id: 2,
    title: "Programming Fundamentals",
    location: "Bu-Ali Sina University",
    description:
      "Covers variables, control structures, loops, and basic programming logic.",
    buttonText: "View Exercises",
    date: "Week 3 - 4",
    iconSrc: shell,
    icon: "school",
  },
  {
    id: 3,
    title: "Pointers & Memory Management",
    location: "Bu-Ali Sina University",
    description:
      "Deep dive into pointers, dynamic memory allocation, and memory management in C.",
    buttonText: "View Examples",
    date: "Week 5 - 6",
    iconSrc: memory,
    icon: "work",
  },
  {
    id: 4,
    title: "Linux Workshop",
    location: "Bu-Ali Sina University",
    description:
      "Hands-on workshop covering basic Linux commands, shell scripting, and file system navigation.",
    buttonText: "Workshop Materials",
    date: "Week 7",
    iconSrc: linux,
    icon: "school",
  },
  {
    id: 5,
    title: "Git Workshop",
    location: "Bu-Ali Sina University",
    description:
      "Learn Git version control: commits, branches, merges, and collaborative workflows.",
    buttonText: "Workshop Guide",
    date: "Week 8",
    iconSrc: git,
    icon: "school",
  },
  {
    id: 6,
    title: "Structs & File I/O",
    location: "Bu-Ali Sina University",
    description:
      "Introduction to structs, reading and writing files in C, and structured data handling.",
    buttonText: "View Exercises",
    date: "Week 9",
    iconSrc: file02,
    icon: "work",
  },
  {
    id: 7,
    title: "Final Project",
    location: "Bu-Ali Sina University",
    description:
      "Apply all learned concepts to develop a complete programming project.",
    buttonText: "Project Details",
    date: "Week 10 - 12",
    iconSrc: "",
    icon: "project",
  },
  {
    id: 8,
    title: "Socket I/O Workshop",
    location: "Bu-Ali Sina University",
    description:
      "Learn network programming basics, TCP/UDP sockets, and client-server communication.",
    buttonText: "Workshop Materials",
    date: "Week 13",
    iconSrc: network,
    icon: "school",
  },
  {
    id: 9,
    title: "GUI & FTXUI Workshop",
    location: "Bu-Ali Sina University",
    description:
      "Hands-on GUI programming using FTXUI library for terminal-based interfaces.",
    buttonText: "Workshop Guide",
    date: "Week 14",
    iconSrc: "",
    icon: "school",
  },
];

export default timelineElements;
