export const scheduleRows = [
  {
    week: 1,
    date: "Mon 08/25",
    lectureNumber: 1,
    lectureTitle: "سلام خوبی چطوری چیکارا میکنی خانواده خوبن؟",
    readings: "جزوه ۱",
    homework:"تمرین 2 " ,
    project:"hi",
    event: "ددددددددد",
  },
  {
    week: 2,
    date: "Sun 01/06",
    lectureNumber: 2,
    lectureTitle: "ککککککککککک",
    readings: "جزوه ۲",
    homework: "تمرین 1 ",
    event: "دددددددددد",
  }, 
   {
    week: 1,
    date: "Mon 08/25",
    lectureNumber: 1,
    lectureTitle: "سلام خوبی چطوری چیکارا میکنی خانواده خوبن؟",
    readings: "جزوه ۱",
    homework:"تمرین 2 " ,
    project:"hi",
    event: "ددددددددد",
  },
  {
    week: 2,
    date: "Sun 01/06",
    lectureNumber: 2,
    lectureTitle: "ککککککککککک",
    readings: "جزوه ۲",
    homework: "تمرین 1 ",
    event: "دددددددددد",
  },
    {
    week: 1,
    date: "Mon 08/25",
    lectureNumber: 1,
    lectureTitle: "سلام خوبی چطوری چیکارا میکنی خانواده خوبن؟",
    readings: "جزوه ۱",
    homework:"تمرین 2 " ,
    project:"hi",
    event: "ددددددددد",
  },
  {
    week: 2,
    date: "Sun 01/06",
    lectureNumber: 2,
    lectureTitle: "ککککککککککک",
    readings: "جزوه ۲",
    homework: "تمرین 1 ",
    event: "دددددددددد",
  },
    {
    week: 1,
    date: "Mon 08/25",
    lectureNumber: 1,
    lectureTitle: "سلام خوبی چطوری چیکارا میکنی خانواده خوبن؟",
    readings: "جزوه ۱",
    homework:"تمرین 2 " ,
    project:"hi",
    event: "ددددددددد",
  },
  {
    week: 2,
    date: "Sun 01/06",
    lectureNumber: 2,
    lectureTitle: "ککککککککککک",
    readings: "جزوه ۲",
    homework: "تمرین 1 ",
    event: "دددددددددد",
  },
];

    /*here we create the rows of our schedule in schedule page*/

